### ISSUE TITLE
aRequireSessionWithParams

### ISSUE THREAD

**Issue by hellboy81** [OXIDprojects/OXIDforge-pages#8]
Please add documentation 

Bitte Dokumentation hinzufügen

Пожалуйста добавьте документацию!

**Comment by kermie** [comment]
Done! 
https://github.com/OXIDprojects/OXIDforge-pages/commit/cfa7ab18dbf524731ff006fdf2efceed8a9c06c3

Thanks for letting us know, dankeschön, огромное спасибо!
